name: Release
on:
  push:
    tags:
      - '*'
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node
      uses: actions/setup-node@v2-beta
      with:
        node-version: 16
        scope: '@barmanjoke'
    - name: Install
      run: npm ci
    - name: Build
      run: npm run build
    - name: Publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{secrets.NPM_REGISTRY_TOKEN}}
