name: Release
on:
  push:
    tags:
      - '*'
jobs:
  release-spec:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node
      uses: actions/setup-node@v2-beta
      with:
        node-version: 16
        scope: '@barmanjoke'
    - name: Install
      run: npm ci
    - name: Build
      run: npm run build
    - name: Publish to GHPR
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_REGISTRY_TOKEN}}
